//! Commercial-tier license gate.
//!
//! The OSS core (everything outside this module) is AGPL-3.0-or-later
//! and ships without any of the capabilities listed in `MONETIZATION.md`.
//! This module itself is governed by `LICENSE-COMMERCIAL` at the repo
//! root (Forseti Commercial License 1.0, SPDX
//! `LicenseRef-Forseti-Commercial-1.0`) — source-available, free for
//! development / evaluation / personal hobbyist use, requires a valid
//! Ed25519-signed Commercial License Key for production use, and forbids
//! operating Forseti as a hosted service for third parties without a
//! separate agreement. Operators with a valid signed license unlock
//! additional features through the runtime check exposed by
//! [`LicenseHandle::feature`].
//!
//! Design:
//!
//! 1. **Offline-signed.** Licenses are Ed25519-signed CBOR blobs (see
//!    `forseti-license` repo for the issuer). Forseti verifies
//!    against [`PUBLIC_KEY_BYTES`] — baked in at build time — and never
//!    phones home. Revocation is yearly-renewal-driven; lifetime
//!    licenses are accepted but documented as un-revocable in
//!    `docs/operator-guide.md`.
//!
//! 2. **Single-license model.** One signed blob per Forseti install,
//!    persisted in the `forseti_license` row (singleton PK). Activated
//!    via `/admin/license`; deactivation is row DELETE.
//!
//! 3. **Lock-free reads.** The verified status sits behind an
//!    [`arc_swap::ArcSwap`] on [`AppState`] so every handler's
//!    `feature()` check is a single atomic pointer load.
//!
//! 4. **Grace period.** Expired licenses keep gated features visible
//!    but read-only for a fixed 30-day window ([`GRACE_DAYS`]) so a
//!    forgotten renewal doesn't blow up production. After the grace
//!    window, gated features hard-gate to the upsell page.
//!
//! See `TODO_LICENSING.md` for the broader scope notes.

pub mod license;
pub mod settings_page;
pub mod store;
pub mod upsell;
pub mod verify;

use license::Feature;
pub use license::{FeatureStatus, LicenseStatus, GRACE_DAYS};

use axum::Router;

use crate::state::AppState;

/// Merge all commercial-tier routes under one entry point. Called from
/// `app::run` to keep the AGPL boundary visible at the composition site.
pub fn router() -> Router<AppState> {
    settings_page::router()
}

use std::sync::Arc;

use arc_swap::ArcSwap;

/// Ed25519 public key Forseti verifies licenses against. Generated by
/// the `forseti-license` issuer and committed to the repo so reproducible
/// builds emit identical binaries. To rotate, re-key the issuer, replace
/// this file, and re-issue every outstanding license (every prior license
/// becomes invalid after rotation — there's no overlap window).
pub const PUBLIC_KEY_BYTES: &[u8; 32] = include_bytes!("pubkey.bin");

/// Runtime handle. Wraps an [`ArcSwap`] so swaps (activate / deactivate)
/// are atomic and reads are wait-free. Cheap to clone; lives on
/// [`crate::state::AppState`].
#[derive(Clone)]
pub struct LicenseHandle {
    inner: Arc<ArcSwap<LicenseStatus>>,
    /// Grace window applied to expired licenses, in days. Fixed at
    /// [`GRACE_DAYS`]; cached here so feature checks stay self-contained.
    grace_days: i64,
}

impl LicenseHandle {
    pub fn new(initial: LicenseStatus, grace_days: i64) -> Self {
        Self {
            inner: Arc::new(ArcSwap::from_pointee(initial)),
            grace_days,
        }
    }

    /// Snapshot the current status. The returned `Arc` doesn't reflect
    /// later swaps; callers that need a long-lived reference should
    /// re-`load()` rather than caching across awaits.
    pub fn status(&self) -> Arc<LicenseStatus> {
        self.inner.load_full()
    }

    /// Swap in a new status. Called by the activate handler and at boot.
    pub fn swap(&self, next: LicenseStatus) {
        self.inner.store(Arc::new(next));
    }

    pub fn grace_days(&self) -> i64 {
        self.grace_days
    }

    /// Feature gate. Returns [`FeatureStatus::Allowed`] when the license
    /// covers `feature` and isn't past its hard-gate date,
    /// [`FeatureStatus::GraceReadOnly`] inside the grace window,
    /// [`FeatureStatus::Locked`] otherwise.
    pub fn feature(&self, feature: Feature) -> FeatureStatus {
        let status = self.status();
        license::evaluate_feature(&status, feature)
    }

    /// Re-classify against `now`, swapping only on a variant change. Returns the new label on transition, else `None`.
    pub fn reclassify(&self, now: chrono::DateTime<chrono::Utc>) -> Option<&'static str> {
        let current = self.status();
        let license = current.license()?;
        let next = license::classify(license.clone(), self.grace_days, now);
        if license::status_variant(&next) == license::status_variant(&current) {
            return None;
        }
        let label = license::status_variant(&next);
        self.swap(next);
        Some(label)
    }
}

use tokio_util::sync::CancellationToken;

/// Hourly tick that re-runs the expiry math so a license that booted `Active` crosses into grace/expired between restarts.
pub fn spawn_reclassify(license: LicenseHandle, shutdown: CancellationToken) {
    use std::time::Duration;
    tokio::spawn(async move {
        let mut ticker = tokio::time::interval(Duration::from_secs(60 * 60));
        ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
        ticker.tick().await; // consume the immediate first tick (boot already classified)
        loop {
            tokio::select! {
                _ = shutdown.cancelled() => {
                    tracing::info!("license reclassify task: shutdown received, exiting");
                    break;
                }
                _ = ticker.tick() => {
                    if let Some(label) = license.reclassify(chrono::Utc::now()) {
                        tracing::warn!(status = label, "license: status transitioned on periodic re-classification");
                    }
                }
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commercial::license::{Feature, License, LicenseStatus};
    use chrono::{Duration, Utc};

    fn active_handle(expires_in_days: i64) -> LicenseHandle {
        let license = License {
            license_id: "test".into(),
            customer: "Test Co".into(),
            email: "t@example.com".into(),
            issued_at: Utc::now(),
            expires_at: Some(Utc::now() + Duration::days(expires_in_days)),
            features: vec![Feature::Orgs],
            max_orgs: None,
            max_seats: None,
        };
        LicenseHandle::new(LicenseStatus::Active(license), GRACE_DAYS)
    }

    #[test]
    fn reclassify_moves_active_into_grace_then_expired() {
        let handle = active_handle(10);
        assert!(matches!(
            handle.feature(Feature::Orgs),
            FeatureStatus::Allowed
        ));

        // 11 days on, the license is one day past expiry — inside grace.
        let into_grace = Utc::now() + Duration::days(11);
        assert_eq!(handle.reclassify(into_grace), Some("Grace"));
        assert!(matches!(
            handle.feature(Feature::Orgs),
            FeatureStatus::GraceReadOnly
        ));

        // Well past the grace window — hard-gated.
        let past_grace = Utc::now() + Duration::days(10 + GRACE_DAYS + 5);
        assert_eq!(handle.reclassify(past_grace), Some("Expired"));
        assert!(matches!(
            handle.feature(Feature::Orgs),
            FeatureStatus::Locked
        ));
    }

    #[test]
    fn reclassify_noop_while_still_active() {
        let handle = active_handle(30);
        assert_eq!(handle.reclassify(Utc::now() + Duration::days(1)), None);
        assert!(matches!(
            handle.feature(Feature::Orgs),
            FeatureStatus::Allowed
        ));
    }
}
