//! Commercial-tier license gate.
//!
//! The OSS core (everything outside this module) is AGPL-3.0-or-later
//! and ships without any of the capabilities listed in `MONETIZATION.md`.
//! This module itself is governed by `LICENSE-COMMERCIAL` at the repo
//! root (Forseti Commercial License 1.0, SPDX
//! `LicenseRef-Forseti-Commercial-1.0`) — source-available, free for
//! development / evaluation / personal hobbyist use, requires a valid
//! Ed25519-signed Commercial License Key for production use, and forbids
//! operating Forseti as a hosted service for third parties without a
//! separate agreement. Operators with a valid signed license unlock
//! additional features through the runtime check exposed by
//! [`LicenseHandle::feature`].
//!
//! Design:
//!
//! 1. **Offline-signed.** Licenses are Ed25519-signed CBOR blobs (see
//!    `forseti-license` repo for the issuer). Forseti verifies
//!    against [`PUBLIC_KEY_BYTES`] — baked in at build time — and never
//!    phones home. Revocation is yearly-renewal-driven; lifetime
//!    licenses are accepted but documented as un-revocable in
//!    `docs/operator-guide.md`.
//!
//! 2. **Single-license model.** One signed blob per Forseti install,
//!    persisted in the `forseti_license` row (singleton PK). Activated
//!    via `/admin/license`; deactivation is row DELETE.
//!
//! 3. **Lock-free reads.** The verified status sits behind an
//!    [`arc_swap::ArcSwap`] on [`AppState`] so every handler's
//!    `feature()` check is a single atomic pointer load.
//!
//! 4. **Grace period.** Expired licenses keep gated features visible
//!    but read-only for `license.grace_days` (default 14) so a
//!    forgotten renewal doesn't blow up production. After the grace
//!    window, gated features hard-gate to the upsell page.
//!
//! See `TODO_LICENSING.md` for the broader scope notes.

pub mod license;
pub mod settings_page;
pub mod store;
pub mod upsell;
pub mod verify;

use license::Feature;
pub use license::{FeatureStatus, LicenseStatus};

use axum::Router;

use crate::state::AppState;

/// Merge all commercial-tier routes under one entry point. Called from
/// `app::run` to keep the AGPL boundary visible at the composition site.
pub fn router() -> Router<AppState> {
    settings_page::router()
}

use std::sync::Arc;

use arc_swap::ArcSwap;

/// Ed25519 public key Forseti verifies licenses against. Generated by
/// the `forseti-license` issuer and committed to the repo so reproducible
/// builds emit identical binaries. To rotate, re-key the issuer, replace
/// this file, and re-issue every outstanding license (every prior license
/// becomes invalid after rotation — there's no overlap window).
pub const PUBLIC_KEY_BYTES: &[u8; 32] = include_bytes!("pubkey.bin");

/// Runtime handle. Wraps an [`ArcSwap`] so swaps (activate / deactivate)
/// are atomic and reads are wait-free. Cheap to clone; lives on
/// [`crate::state::AppState`].
#[derive(Clone)]
pub struct LicenseHandle {
    inner: Arc<ArcSwap<LicenseStatus>>,
    /// Grace window applied to expired licenses, in days. Cached at boot
    /// from `config.toml::license.grace_days` so feature checks don't
    /// re-touch the config struct.
    grace_days: i64,
}

impl LicenseHandle {
    pub fn new(initial: LicenseStatus, grace_days: i64) -> Self {
        Self {
            inner: Arc::new(ArcSwap::from_pointee(initial)),
            grace_days,
        }
    }

    /// Snapshot the current status. The returned `Arc` doesn't reflect
    /// later swaps; callers that need a long-lived reference should
    /// re-`load()` rather than caching across awaits.
    pub fn status(&self) -> Arc<LicenseStatus> {
        self.inner.load_full()
    }

    /// Swap in a new status. Called by the activate handler and at boot.
    pub fn swap(&self, next: LicenseStatus) {
        self.inner.store(Arc::new(next));
    }

    pub fn grace_days(&self) -> i64 {
        self.grace_days
    }

    /// Feature gate. Returns [`FeatureStatus::Allowed`] when the license
    /// covers `feature` and isn't past its hard-gate date,
    /// [`FeatureStatus::GraceReadOnly`] inside the grace window,
    /// [`FeatureStatus::Locked`] otherwise.
    pub fn feature(&self, feature: Feature) -> FeatureStatus {
        let status = self.status();
        license::evaluate_feature(&status, feature)
    }
}
