//! `libnss_forseti.so.2` — a thin NSS module resolving passwd/group via the
//! local forseti-unixd socket. libc dlopens this into every process that does a
//! name lookup (incl. setuid sshd/sudo), so it links only proto + the blocking
//! socket client (timeouts + MSG_NOSIGNAL + fail-open None). No network, no
//! secrets, no runtime in this `.so`.
//!
//! The `_nss_forseti_*` C symbols (incl. setpwent/getpwent_r/endpwent and the
//! ERANGE buffer packing) are generated by `libnss`'s hook macros — we only
//! implement the 3-method trait per database.

use forseti_unix_client::query;
use forseti_unix_proto::{self as proto, ClientRequest, ClientResponse};
use libnss::group::{Group, GroupHooks};
use libnss::libnss_group_hooks;
use libnss::libnss_passwd_hooks;
use libnss::passwd::{Passwd, PasswdHooks};
use libnss::interop::Response;
use std::time::Duration;

const DEFAULT_SOCKET: &str = "/run/forseti/unixd.sock";
const TIMEOUT: Duration = Duration::from_secs(2);

/// Socket path: `FORSETI_UNIXD_SOCKET` override or the default run path.
fn socket_path() -> String {
    std::env::var("FORSETI_UNIXD_SOCKET").unwrap_or_else(|_| DEFAULT_SOCKET.to_string())
}

fn to_passwd(e: proto::PasswdEntry) -> Passwd {
    Passwd {
        name: e.name,
        passwd: "x".to_string(),
        uid: e.uid,
        gid: e.gid,
        gecos: e.gecos,
        dir: e.dir,
        shell: e.shell,
    }
}

fn to_group(e: proto::GroupEntry) -> Group {
    Group {
        name: e.name,
        passwd: "x".to_string(),
        gid: e.gid,
        members: e.members,
    }
}

struct ForsetiPasswd;

impl PasswdHooks for ForsetiPasswd {
    fn get_all_entries() -> Response<Vec<Passwd>> {
        match query(&socket_path(), &ClientRequest::PasswdAll, TIMEOUT) {
            Some(ClientResponse::PasswdList(v)) => {
                Response::Success(v.into_iter().map(to_passwd).collect())
            }
            // Empty authoritative answer: getent cleanly falls through to `files`.
            _ => Response::Success(vec![]),
        }
    }

    fn get_entry_by_uid(uid: libc::uid_t) -> Response<Passwd> {
        match query(&socket_path(), &ClientRequest::PasswdByUid(uid), TIMEOUT) {
            Some(ClientResponse::Passwd(Some(e))) => Response::Success(to_passwd(e)),
            _ => Response::NotFound,
        }
    }

    fn get_entry_by_name(name: String) -> Response<Passwd> {
        match query(&socket_path(), &ClientRequest::PasswdByName(name), TIMEOUT) {
            Some(ClientResponse::Passwd(Some(e))) => Response::Success(to_passwd(e)),
            _ => Response::NotFound,
        }
    }
}

struct ForsetiGroup;

impl GroupHooks for ForsetiGroup {
    fn get_all_entries() -> Response<Vec<Group>> {
        match query(&socket_path(), &ClientRequest::GroupAll, TIMEOUT) {
            Some(ClientResponse::GroupList(v)) => {
                Response::Success(v.into_iter().map(to_group).collect())
            }
            _ => Response::Success(vec![]),
        }
    }

    fn get_entry_by_gid(gid: libc::gid_t) -> Response<Group> {
        match query(&socket_path(), &ClientRequest::GroupByGid(gid), TIMEOUT) {
            Some(ClientResponse::Group(Some(e))) => Response::Success(to_group(e)),
            _ => Response::NotFound,
        }
    }

    fn get_entry_by_name(name: String) -> Response<Group> {
        match query(&socket_path(), &ClientRequest::GroupByName(name), TIMEOUT) {
            Some(ClientResponse::Group(Some(e))) => Response::Success(to_group(e)),
            _ => Response::NotFound,
        }
    }
}

libnss_passwd_hooks!(forseti, ForsetiPasswd);
libnss_group_hooks!(forseti, ForsetiGroup);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn passwd_entry_converts() {
        let e = proto::PasswdEntry {
            name: "alice".into(),
            uid: 1000001,
            gid: 2000001,
            gecos: String::new(),
            dir: "/home/alice".into(),
            shell: "/bin/sh".into(),
        };
        let p = to_passwd(e);
        assert_eq!(p.name, "alice");
        assert_eq!(p.passwd, "x");
        assert_eq!(p.uid, 1000001);
        assert_eq!(p.gid, 2000001);
        assert_eq!(p.gecos, "");
        assert_eq!(p.dir, "/home/alice");
        assert_eq!(p.shell, "/bin/sh");
    }

    #[test]
    fn group_entry_converts() {
        let e = proto::GroupEntry {
            name: "staff".into(),
            gid: 2000001,
            members: vec!["alice".into(), "bob".into()],
        };
        let g = to_group(e);
        assert_eq!(g.name, "staff");
        assert_eq!(g.passwd, "x");
        assert_eq!(g.gid, 2000001);
        assert_eq!(g.members, vec!["alice".to_string(), "bob".to_string()]);
    }

    #[test]
    fn socket_path_defaults() {
        // Only assert the default when the override isn't set in the env.
        if std::env::var_os("FORSETI_UNIXD_SOCKET").is_none() {
            assert_eq!(socket_path(), DEFAULT_SOCKET);
        }
    }
}
