//! `libnss_forseti.so.2` — a thin NSS module resolving passwd/group via the
//! local forseti-unixd socket. libc dlopens this into every process that does a
//! name lookup (incl. setuid sshd/sudo), so it links only proto + the blocking
//! socket client (timeouts + MSG_NOSIGNAL + fail-open None). No network, no
//! secrets, no runtime in this `.so`.
//!
//! The `_nss_forseti_*` C symbols (incl. setpwent/getpwent_r/endpwent and the
//! ERANGE buffer packing) are generated by `libnss`'s hook macros — we only
//! implement the 3-method trait per database.

use forseti_unix_client::query;
use forseti_unix_proto::{self as proto, ClientRequest, ClientResponse};
use libnss::group::{Group, GroupHooks};
use libnss::interop::Response;
use libnss::libnss_group_hooks;
use libnss::libnss_passwd_hooks;
use libnss::passwd::{Passwd, PasswdHooks};
use std::time::Duration;

// Fixed, never read from the environment: this .so runs inside setuid/root
// processes that keep the caller's environ, so an env override would let a
// local user substitute their own socket.
const SOCKET: &str = "/run/forseti/unixd.sock";
const TIMEOUT: Duration = Duration::from_secs(2);

/// An entry field carrying an interior NUL can't be written to the C buffer:
/// `libnss`'s writer builds a `CString` and unwraps, so it panics, and a panic
/// crossing the C ABI aborts whatever dlopened us - sshd, sudo, `getent`. The
/// module is a normal crates.io dependency, not vendored here, so the check
/// belongs on this side of the call. A field like that can only come from a
/// corrupt or hostile record, so dropping the entry loses nothing real.
fn has_nul(fields: &[&str]) -> bool {
    fields.iter().any(|f| f.contains('\0'))
}

fn to_passwd(e: proto::PasswdEntry) -> Option<Passwd> {
    if has_nul(&[&e.name, &e.gecos, &e.dir, &e.shell]) {
        return None;
    }
    Some(Passwd {
        name: e.name,
        passwd: "x".to_string(),
        uid: e.uid,
        gid: e.gid,
        gecos: e.gecos,
        dir: e.dir,
        shell: e.shell,
    })
}

fn to_group(e: proto::GroupEntry) -> Option<Group> {
    if has_nul(&[&e.name]) || e.members.iter().any(|m| m.contains('\0')) {
        return None;
    }
    Some(Group {
        name: e.name,
        passwd: "x".to_string(),
        gid: e.gid,
        members: e.members,
    })
}

struct ForsetiPasswd;

impl PasswdHooks for ForsetiPasswd {
    fn get_all_entries() -> Response<Vec<Passwd>> {
        match query(SOCKET, &ClientRequest::PasswdAll, TIMEOUT) {
            Some(ClientResponse::PasswdList(v)) => {
                Response::Success(v.into_iter().filter_map(to_passwd).collect())
            }
            // Empty authoritative answer: getent cleanly falls through to `files`.
            _ => Response::Success(vec![]),
        }
    }

    fn get_entry_by_uid(uid: libc::uid_t) -> Response<Passwd> {
        match query(SOCKET, &ClientRequest::PasswdByUid(uid), TIMEOUT) {
            Some(ClientResponse::Passwd(Some(e))) => match to_passwd(e) {
                Some(p) => Response::Success(p),
                None => Response::NotFound,
            },
            _ => Response::NotFound,
        }
    }

    fn get_entry_by_name(name: String) -> Response<Passwd> {
        match query(SOCKET, &ClientRequest::PasswdByName(name), TIMEOUT) {
            Some(ClientResponse::Passwd(Some(e))) => match to_passwd(e) {
                Some(p) => Response::Success(p),
                None => Response::NotFound,
            },
            _ => Response::NotFound,
        }
    }
}

struct ForsetiGroup;

impl GroupHooks for ForsetiGroup {
    fn get_all_entries() -> Response<Vec<Group>> {
        match query(SOCKET, &ClientRequest::GroupAll, TIMEOUT) {
            Some(ClientResponse::GroupList(v)) => {
                Response::Success(v.into_iter().filter_map(to_group).collect())
            }
            _ => Response::Success(vec![]),
        }
    }

    fn get_entry_by_gid(gid: libc::gid_t) -> Response<Group> {
        match query(SOCKET, &ClientRequest::GroupByGid(gid), TIMEOUT) {
            Some(ClientResponse::Group(Some(e))) => match to_group(e) {
                Some(g) => Response::Success(g),
                None => Response::NotFound,
            },
            _ => Response::NotFound,
        }
    }

    fn get_entry_by_name(name: String) -> Response<Group> {
        match query(SOCKET, &ClientRequest::GroupByName(name), TIMEOUT) {
            Some(ClientResponse::Group(Some(e))) => match to_group(e) {
                Some(g) => Response::Success(g),
                None => Response::NotFound,
            },
            _ => Response::NotFound,
        }
    }
}

libnss_passwd_hooks!(forseti, ForsetiPasswd);
libnss_group_hooks!(forseti, ForsetiGroup);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn passwd_entry_converts() {
        let e = proto::PasswdEntry {
            name: "alice".into(),
            uid: 1000001,
            gid: 2000001,
            gecos: String::new(),
            dir: "/home/alice".into(),
            shell: "/bin/sh".into(),
        };
        let p = to_passwd(e).expect("clean entry converts");
        assert_eq!(p.name, "alice");
        assert_eq!(p.passwd, "x");
        assert_eq!(p.uid, 1000001);
        assert_eq!(p.gid, 2000001);
        assert_eq!(p.gecos, "");
        assert_eq!(p.dir, "/home/alice");
        assert_eq!(p.shell, "/bin/sh");
    }

    #[test]
    fn group_entry_converts() {
        let e = proto::GroupEntry {
            name: "staff".into(),
            gid: 2000001,
            members: vec!["alice".into(), "bob".into()],
        };
        let g = to_group(e).expect("clean entry converts");
        assert_eq!(g.name, "staff");
        assert_eq!(g.passwd, "x");
        assert_eq!(g.gid, 2000001);
        assert_eq!(g.members, vec!["alice".to_string(), "bob".to_string()]);
    }

    #[test]
    fn passwd_entry_with_interior_nul_is_dropped() {
        for e in [
            proto::PasswdEntry {
                name: "ali\0ce".into(),
                uid: 1000001,
                gid: 2000001,
                gecos: String::new(),
                dir: "/home/alice".into(),
                shell: "/bin/sh".into(),
            },
            proto::PasswdEntry {
                name: "alice".into(),
                uid: 1000001,
                gid: 2000001,
                gecos: String::new(),
                dir: "/home/alice".into(),
                shell: "/bin/sh\0/bin/evil".into(),
            },
        ] {
            assert!(
                to_passwd(e).is_none(),
                "a NUL-bearing field must drop the entry"
            );
        }
    }

    #[test]
    fn group_entry_with_interior_nul_is_dropped() {
        let named = proto::GroupEntry {
            name: "sta\0ff".into(),
            gid: 2000001,
            members: vec!["alice".into()],
        };
        assert!(to_group(named).is_none());

        let membered = proto::GroupEntry {
            name: "staff".into(),
            gid: 2000001,
            members: vec!["alice".into(), "bo\0b".into()],
        };
        assert!(to_group(membered).is_none());
    }
}
